name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Build Electron apps (Mac + Windows)
      run: npm run electron-pack-all
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/Karta Medycznych Czynności Ratunkowych 1.0.0.exe
          dist/Karta-Medycznych-Czynnosci-Ratunkowych-mac.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}